version: '2'
services:
    zoo-1:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        volumes:
            - ./data/zoo-1:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo-1:2888:3888
            ZOO_DATA_LOG_DIR: /opt/persist/logs
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATADIR: /opt/persist/data

